import { Montserrat } from "next/font/google";
import "./globals.css";
import Circles from "@/components/Circles";

const roboto = Montserrat({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Dev Rokon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} wrapper`}>
        {children}

        <ul className="animate-bg">
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
          <li></li>
        </ul>
        <Circles />
      </body>
    </html>
  );
}
