import { Montserrat } from 'next/font/google'
import "./globals.css";

const roboto = Montserrat({ subsets: ['latin'], weight:['400'] })

export const metadata = {
  title: "Dev Rokon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className}`}
      >
        {children}
      </body>
    </html>
  );
}